// <auto-generated />
using System;
using AllinOrder_Shahaf_Ofir_Snir.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AllinOrder_Shahaf_Ofir_Snir.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("AllinOrder_Shahaf_Ofir_Snir.Shared.Entities.Game", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublish")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("AllinOrder_Shahaf_Ofir_Snir.Shared.Entities.Item", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemContent")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemPlace")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("QuestionID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("AllinOrder_Shahaf_Ofir_Snir.Shared.Entities.Question", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstText")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastText")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionPic")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionText")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("GameID");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("AllinOrder_Shahaf_Ofir_Snir.Shared.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserEmail")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AllinOrder_Shahaf_Ofir_Snir.Shared.Entities.Game", b =>
                {
                    b.HasOne("AllinOrder_Shahaf_Ofir_Snir.Shared.Entities.User", "GameUser")
                        .WithMany("UserGames")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameUser");
                });

            modelBuilder.Entity("AllinOrder_Shahaf_Ofir_Snir.Shared.Entities.Item", b =>
                {
                    b.HasOne("AllinOrder_Shahaf_Ofir_Snir.Shared.Entities.Question", "ItemQuestion")
                        .WithMany("QuestionItems")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemQuestion");
                });

            modelBuilder.Entity("AllinOrder_Shahaf_Ofir_Snir.Shared.Entities.Question", b =>
                {
                    b.HasOne("AllinOrder_Shahaf_Ofir_Snir.Shared.Entities.Game", "QuestionGame")
                        .WithMany("GameQuestions")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionGame");
                });

            modelBuilder.Entity("AllinOrder_Shahaf_Ofir_Snir.Shared.Entities.Game", b =>
                {
                    b.Navigation("GameQuestions");
                });

            modelBuilder.Entity("AllinOrder_Shahaf_Ofir_Snir.Shared.Entities.Question", b =>
                {
                    b.Navigation("QuestionItems");
                });

            modelBuilder.Entity("AllinOrder_Shahaf_Ofir_Snir.Shared.Entities.User", b =>
                {
                    b.Navigation("UserGames");
                });
#pragma warning restore 612, 618
        }
    }
}
